import scala.collection.mutable.ListBuffer

object TileUtilities {
  def createInitialBag(): Bag = {
    val buffer: ListBuffer[Tile] = new ListBuffer[Tile]
    for (_ <- 0 until 9) buffer += A()
    for (_ <- 0 until 2) buffer += B()
    for (_ <- 0 until 2) buffer += C()
    for (_ <- 0 until 4) buffer += D()
    for (_ <- 0 until 12) buffer += E()
    for (_ <- 0 until 2) buffer += F()
    for (_ <- 0 until 3) buffer += G()
    for (_ <- 0 until 2) buffer += H()
    for (_ <- 0 until 9) buffer += I()
    for (_ <- 0 until 1) buffer += J()
    for (_ <- 0 until 1) buffer += K()
    for (_ <- 0 until 4) buffer += L()
    for (_ <- 0 until 2) buffer += M()
    for (_ <- 0 until 6) buffer += N()
    for (_ <- 0 until 8) buffer += O()
    for (_ <- 0 until 2) buffer += P()
    for (_ <- 0 until 1) buffer += Q()
    for (_ <- 0 until 6) buffer += R()
    for (_ <- 0 until 4) buffer += S()
    for (_ <- 0 until 6) buffer += T()
    for (_ <- 0 until 4) buffer += U()
    for (_ <- 0 until 2) buffer += V()
    for (_ <- 0 until 2) buffer += W()
    for (_ <- 0 until 1) buffer += X()
    for (_ <- 0 until 2) buffer += Y()
    for (_ <- 0 until 1) buffer += Z()
    for (_ <- 0 until 2) buffer += BLANK()
    new Bag(buffer)
  }

  def A(): Tile = new Tile('A', 1)
  def B(): Tile = new Tile('B', 3)
  def C(): Tile = new Tile('C', 3)
  def D(): Tile = new Tile('D', 2)
  def E(): Tile = new Tile('E', 1)
  def F(): Tile = new Tile('F', 4)
  def G(): Tile = new Tile('G', 2)
  def H(): Tile = new Tile('H', 4)
  def I(): Tile = new Tile('I', 1)
  def J(): Tile = new Tile('J', 8)
  def K(): Tile = new Tile('K', 5)
  def L(): Tile = new Tile('L', 1)
  def M(): Tile = new Tile('M', 3)
  def N(): Tile = new Tile('N', 1)
  def O(): Tile = new Tile('O', 1)
  def P(): Tile = new Tile('P', 3)
  def Q(): Tile = new Tile('Q', 10)
  def R(): Tile = new Tile('R', 1)
  def S(): Tile = new Tile('S', 1)
  def T(): Tile = new Tile('T', 1)
  def U(): Tile = new Tile('U', 1)
  def V(): Tile = new Tile('V', 4)
  def W(): Tile = new Tile('W', 4)
  def X(): Tile = new Tile('X', 8)
  def Y(): Tile = new Tile('Y', 4)
  def Z(): Tile = new Tile('Z', 10)
  def BLANK(): Tile = new Tile(' ', 0)
}
